### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by raj5287** [digamma-ai/timeextractor#14]
While doing `pip install pytimeextractor`, am getting this error :
```
 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-5_9_5mn5\\pytimeextractor\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-5_9_5mn5\\pytimeextractor\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-5_9_5mn5\pytimeextractor\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-5_9_5mn5\pytimeextractor\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-5_9_5mn5\pytimeextractor\setup.py", line 10, in <module>
        long_description=readme(),
      File "C:\Users\user\AppData\Local\Temp\pip-install-5_9_5mn5\pytimeextractor\setup.py", line 5, in readme
        return f.read()
      File "C:\Users\user\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 528: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I am using python version 3.7.6 and anaconda version 4.8.3 . Can you help me out here?

**Comment by alwhelan22** [comment]
Same except issues with determining JDK_HOME and JRE_HOME

```
 ✘  ~  pip install pytimeextractor==0.1.4
Collecting pytimeextractor==0.1.4
  Using cached pytimeextractor-0.1.4.tar.gz (3.0 MB)
Collecting pyjnius==1.1.1
  Using cached pyjnius-1.1.1.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ze212ws_/pyjnius_9acfd563681d433d95fb7ba30867083d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ze212ws_/pyjnius_9acfd563681d433d95fb7ba30867083d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xupwsh4o
         cwd: /tmp/pip-install-ze212ws_/pyjnius_9acfd563681d433d95fb7ba30867083d/
    Complete output (7 lines):
    readlink: missing operand
    Try 'readlink --help' for more information.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ze212ws_/pyjnius_9acfd563681d433d95fb7ba30867083d/setup.py", line 111, in <module>
        raise Exception('Unable to determine JDK_HOME')
    Exception: Unable to determine JDK_HOME
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/34/c7/d1f800839f64f7439ca5d746ad35063f4a65bd5390690ef9f1176a900016/pyjnius-1.1.1.tar.gz#sha256=1fa37e5ece0c118f47085daea7dd3b4b8b300cc1bcb5edc8feac85a582942964 (from https://pypi.org/simple/pyjnius/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyjnius==1.1.1 (from pytimeextractor)
ERROR: No matching distribution found for pyjnius==1.1.1
```

**Comment by wallon-ai** [comment]
same error
